"""empty message

Revision ID: 2769c8a19d15
Revises: ea3ab9f58d25
Create Date: 2021-07-20 17:56:01.872480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2769c8a19d15'
down_revision = 'ea3ab9f58d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pivo_carrinho_produtos', 'lojista_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('vendas', sa.Column('lojista_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendas', 'lojista_id')
    op.alter_column('pivo_carrinho_produtos', 'lojista_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
