"""include carrinho_id to cliente

Revision ID: 36b664cbc433
Revises: b76f0118d13a
Create Date: 2021-07-15 10:27:33.069007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b664cbc433'
down_revision = 'b76f0118d13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('carrinho_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'carrinho_id')
    # ### end Alembic commands ###
