"""criacao da tabela endereco

Revision ID: 3ae272dae32e
Revises: 
Create Date: 2021-07-12 11:18:42.652612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae272dae32e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endereco',
    sa.Column('endereco_int', sa.Integer(), nullable=False),
    sa.Column('logadouro', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=255), nullable=False),
    sa.Column('complemento', sa.String(length=255), nullable=False),
    sa.Column('bairro', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('endereco_int')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endereco')
    # ### end Alembic commands ###
