"""criacao da tabela categorias de produtos

Revision ID: 4d22ea6087a2
Revises: 831ff5bc7e3e
Create Date: 2021-07-12 11:45:03.256745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d22ea6087a2'
down_revision = '831ff5bc7e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('categoria_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorias')
    # ### end Alembic commands ###
