"""change:atribute

Revision ID: 5db3c5b6d885
Revises: 41e28ec5e82f
Create Date: 2021-07-14 21:24:46.696336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db3c5b6d885'
down_revision = '41e28ec5e82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endereco', sa.Column('logradouro', sa.String(length=255), nullable=False))
    op.drop_column('endereco', 'logadouro')
    op.alter_column('produtos', 'lojista_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('produtos', 'categoria_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('vendas_carrinho_id_fkey', 'vendas', type_='foreignkey')
    op.create_foreign_key(None, 'vendas', 'carrinho', ['carrinho_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendas', type_='foreignkey')
    op.create_foreign_key('vendas_carrinho_id_fkey', 'vendas', 'clientes', ['carrinho_id'], ['id'])
    op.alter_column('produtos', 'categoria_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('produtos', 'lojista_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('endereco', sa.Column('logadouro', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('endereco', 'logradouro')
    # ### end Alembic commands ###
