"""empty message

Revision ID: 6c9f1a89d8b2
Revises: f16a54c7bab3
Create Date: 2021-07-19 11:21:25.373067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9f1a89d8b2'
down_revision = 'f16a54c7bab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('endereco', 'complemento',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('produtos', sa.Column('modelo', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'produtos', ['modelo'])
    op.drop_column('produtos', 'fabricante')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('fabricante', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'produtos', type_='unique')
    op.drop_column('produtos', 'modelo')
    op.alter_column('endereco', 'complemento',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
