"""criacao da tabela Cliente com relacionamento com endereco

Revision ID: 831ff5bc7e3e
Revises: 3ae272dae32e
Create Date: 2021-07-12 11:34:18.748824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831ff5bc7e3e'
down_revision = '3ae272dae32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['endereco.endereco_int'], ),
    sa.PrimaryKeyConstraint('cliente_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    # ### end Alembic commands ###
