"""change: atribbute product for False

Revision ID: a7b8b0ad8bc2
Revises: 5db3c5b6d885
Create Date: 2021-07-14 21:30:23.790706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b8b0ad8bc2'
down_revision = '5db3c5b6d885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produtos', 'lojista_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('produtos', 'categoria_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produtos', 'categoria_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('produtos', 'lojista_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
