"""add column status_id to table carrinho

Revision ID: b76f0118d13a
Revises: 80d4af6ea346
Create Date: 2021-07-15 00:11:34.861598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b76f0118d13a'
down_revision = '80d4af6ea346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrinho', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'carrinho', 'status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carrinho', type_='foreignkey')
    op.drop_column('carrinho', 'status_id')
    # ### end Alembic commands ###
