"""empty message

Revision ID: c73d608bd0ff
Revises: 
Create Date: 2021-07-21 20:00:25.596614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73d608bd0ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=255), nullable=False),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('endereco_id', sa.Integer(), nullable=True),
    sa.Column('carrinho_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['endereco_id'], ['endereco.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lojistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['endereco_id'], ['endereco.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('carrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('marca', sa.String(length=255), nullable=False),
    sa.Column('qtd_estoque', sa.Float(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('lojista_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['lojista_id'], ['lojistas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modelo')
    )
    op.create_table('pivo_carrinho_produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('data_prod_inserida', sa.DateTime(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('carrinho_id', sa.Integer(), nullable=False),
    sa.Column('lojista_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinho.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('nota_fiscal', sa.String(length=255), nullable=True),
    sa.Column('cupom_id', sa.Integer(), nullable=False),
    sa.Column('data_venda', sa.DateTime(), nullable=True),
    sa.Column('lojista_id', sa.Integer(), nullable=True),
    sa.Column('endereco_entrega_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('carrinho_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinho.id'], ),
    sa.ForeignKeyConstraint(['endereco_entrega_id'], ['endereco.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendas')
    op.drop_table('pivo_carrinho_produtos')
    op.drop_table('produtos')
    op.drop_table('carrinho')
    op.drop_table('lojistas')
    op.drop_table('clientes')
    op.drop_table('status')
    op.drop_table('endereco')
    op.drop_table('categorias')
    # ### end Alembic commands ###
