"""empty message

Revision ID: f16a54c7bab3
Revises: 36b664cbc433
Create Date: 2021-07-16 17:44:38.664874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16a54c7bab3'
down_revision = '36b664cbc433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pivo_carrinho_produtos', sa.Column('lojista_id', sa.Integer(), nullable=True))
    op.alter_column('vendas', 'nota_fiscal',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendas', 'nota_fiscal',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('pivo_carrinho_produtos', 'lojista_id')
    # ### end Alembic commands ###
